# Generated by Django 3.0.6 on 2020-05-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['wins']},
        ),
        migrations.AddField(
            model_name='team',
            name='conference',
            field=models.CharField(blank=True, choices=[('WESTERN', 'Western'), ('EASTERN', 'Eastern')], max_length=30),
        ),
    ]
